import json
import os
import urllib.parse
import urllib.request
from pathlib import Path


def read_json(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path, value):
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")


def raw_dir():
    target = Path(os.environ.get("RWB_RAW_RESPONSES_DIR") or Path(os.environ["RWB_ARTIFACT_DIR"]) / "raw_responses")
    target.mkdir(parents=True, exist_ok=True)
    return target


def read_optional_input(name, fallback):
    path = os.environ.get(name)
    if path and Path(path).exists():
        return read_json(path)
    return fallback


def request_json(url, token, payload):
    data = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        method="POST",
        headers={
            "authorization": f"Bearer {token}",
            "content-type": "application/json",
            "accept": "application/json",
        },
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        body = response.read().decode("utf-8")
        parsed = json.loads(body) if body.strip() else {}
        return {"status_code": response.status, "headers": dict(response.headers), "body": parsed}


def default_metadata(params):
    metadata = params.get("metadata", {})
    return {
        "title": metadata.get("title", "Atrium reproducibility bundle"),
        "upload_type": metadata.get("upload_type", "dataset"),
        "description": metadata.get("description", "Reproducibility bundle generated by Atrium."),
        "creators": metadata.get("creators", [{"name": metadata.get("creator_name", "Atrium User")}]),
        **{k: v for k, v in metadata.items() if k not in {"title", "upload_type", "description", "creators", "creator_name"}},
    }


def main():
    params = read_json(os.environ["RWB_PARAMS"])
    mode = params.get("source_mode", "fixture")
    if mode == "snapshot":
        write_json(os.environ["RWB_OUTPUT_zenodo_deposit"], read_json(params["snapshot_path"]))
        return

    payload = {
        "service": "zenodo",
        "dry_run": bool(params.get("dry_run", True)),
        "submit_live": bool(params.get("submit_live", False)),
        "bundle": read_optional_input("RWB_INPUT_bundle_manifest", {}),
        "request": {"metadata": default_metadata(params)},
    }

    if mode != "live_archived" or payload["dry_run"] or not payload["submit_live"]:
        payload["status"] = "dry_run" if payload["dry_run"] else "request_archived_not_submitted"
        write_json(raw_dir() / "zenodo-deposit_request.json", payload["request"])
        write_json(os.environ["RWB_OUTPUT_zenodo_deposit"], payload)
        return

    token = os.environ.get("RWB_ZENODO_TOKEN")
    if not token:
        raise RuntimeError("zenodo-deposit live submission requires RWB_ZENODO_TOKEN")

    api_base = params.get("api_base", "https://zenodo.org/api").rstrip("/")
    endpoint = f"{api_base}/deposit/depositions"
    archive_request = {"endpoint": endpoint, "body": payload["request"]}
    write_json(raw_dir() / "zenodo-deposit_request.json", archive_request)
    response = request_json(endpoint, token, payload["request"])
    write_json(raw_dir() / "zenodo-deposit_response.json", response)

    body = response.get("body", {})
    payload.update({
        "status": "created_draft",
        "endpoint": endpoint,
        "deposition_id": body.get("id"),
        "record_url": body.get("links", {}).get("html"),
        "doi": body.get("metadata", {}).get("doi"),
        "response_status": response.get("status_code"),
    })
    write_json(os.environ["RWB_OUTPUT_zenodo_deposit"], payload)


if __name__ == "__main__":
    main()
