import json
import os
import urllib.request
from pathlib import Path


def read_json(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path, value):
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")


def raw_dir():
    target = Path(os.environ.get("RWB_RAW_RESPONSES_DIR") or Path(os.environ["RWB_ARTIFACT_DIR"]) / "raw_responses")
    target.mkdir(parents=True, exist_ok=True)
    return target


def read_optional_input(name, fallback):
    path = os.environ.get(name)
    if path and Path(path).exists():
        return read_json(path)
    return fallback


def request_json(url, token, payload):
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        method="POST",
        headers={
            "authorization": f"token {token}",
            "content-type": "application/json",
            "accept": "application/json",
        },
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        body = response.read().decode("utf-8")
        parsed = json.loads(body) if body.strip() else {}
        return {"status_code": response.status, "headers": dict(response.headers), "body": parsed}


def default_article(params):
    metadata = params.get("metadata", {})
    return {
        "title": metadata.get("title", "Atrium reproducibility bundle"),
        "description": metadata.get("description", "Reproducibility bundle generated by Atrium."),
        "defined_type": metadata.get("defined_type", "dataset"),
        "tags": metadata.get("tags", ["atrium", "reproducibility"]),
        **{k: v for k, v in metadata.items() if k not in {"title", "description", "defined_type", "tags"}},
    }


def main():
    params = read_json(os.environ["RWB_PARAMS"])
    mode = params.get("source_mode", "fixture")
    if mode == "snapshot":
        write_json(os.environ["RWB_OUTPUT_figshare_deposit"], read_json(params["snapshot_path"]))
        return

    payload = {
        "service": "figshare",
        "dry_run": bool(params.get("dry_run", True)),
        "submit_live": bool(params.get("submit_live", False)),
        "bundle": read_optional_input("RWB_INPUT_bundle_manifest", {}),
        "request": default_article(params),
    }

    if mode != "live_archived" or payload["dry_run"] or not payload["submit_live"]:
        payload["status"] = "dry_run" if payload["dry_run"] else "request_archived_not_submitted"
        write_json(raw_dir() / "figshare-deposit_request.json", payload["request"])
        write_json(os.environ["RWB_OUTPUT_figshare_deposit"], payload)
        return

    token = os.environ.get("RWB_FIGSHARE_TOKEN")
    if not token:
        raise RuntimeError("figshare-deposit live submission requires RWB_FIGSHARE_TOKEN")

    endpoint = params.get("api_base", "https://api.figshare.com/v2").rstrip("/") + "/account/articles"
    write_json(raw_dir() / "figshare-deposit_request.json", {"endpoint": endpoint, "body": payload["request"]})
    response = request_json(endpoint, token, payload["request"])
    write_json(raw_dir() / "figshare-deposit_response.json", response)

    body = response.get("body", {})
    payload.update({
        "status": "created_draft",
        "endpoint": endpoint,
        "article_id": body.get("entity_id") or body.get("id"),
        "location": response.get("headers", {}).get("Location"),
        "response_status": response.get("status_code"),
    })
    write_json(os.environ["RWB_OUTPUT_figshare_deposit"], payload)


if __name__ == "__main__":
    main()
